title: My coding expirience
author: dieplumpe
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is about my expirience in learning coding with FreeCodeCamp

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  dieplumpe # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
